title: SHaaDiThakaRashardRiCoTHakA
description: compiling thoughts
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true